---
title: ""
output:
  html_document:
    pandoc_args: !expr 'list(paste0("--filter=", system.file("filters/tabs.R", package="remarker")))'
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(shiny)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
gridlayout::use_gridlayout_rmd(selector_prefix  = "#section-")
```

```{gridlayout}
|      |        |           |           |
|------|--------|-----------|-----------|
|1rem  |200px   |1fr        |1fr        |
|100px |header  |header     |header     |
|1fr   |sidebar |main_panel |main_panel |
|1fr   |sidebar |main_panel |main_panel |
```


# Header panel {#header}

Header panel content


# Main panel {#main_panel}

Text one two three *italic*. Text in 'single quotes', "double quotes".


## {.tabs tabtype="tabsetPanel"}


### First subsection

Some *text* in a *paragraph*. This section has a bulletted list.

-   A bullet item
-   Another bullet item

```{r}
1+1
```

<!-- ##### Inner tabset panel {.tabset2} -->

<!-- ###### Inner tab -->

<!-- asdf -->

<!-- ###### Another inner tab -->

<!-- xyz -->

### `r icon("calendar")` Second subsection

This is the next subsection.

```{r, echo=FALSE}
sliderInput("bins", "Number of bins:", min = 1, max = 50, value = 30)
plotOutput("distPlot")
```

```{r, context="server"}
output$distPlot <- renderPlot({
  x <- faithful[, 2]  # Old Faithful Geyser data
  bins <- seq(min(x), max(x), length.out = input$bins + 1)
  hist(x, breaks = bins, col = 'darkgray', border = 'white')
})
```



# Sidebar {#sidebar}

sidebar stuff
